### ISSUE TITLE
A question about Vulnerability Search in README

### ISSUE THREAD

**Issue by DuckRui** [Asteria-BCSD/Asteria#2]
Hi, I am trying  to use this great tool but seems like I get some trouble.
I have installed it successfully. When I run 'python3 application/main_app.py data/vul.sqlite data/NetGear_Small.sqlite', it reports an error
![image](https://user-images.githubusercontent.com/41203418/147430660-7ca36710-c85b-4bcd-9b37-f74d6f580561.png)

I noticed that in the log_result function, the value of result was abnormal, the result is 
![image](https://user-images.githubusercontent.com/41203418/147430265-99bc6e79-7b52-43e3-86df-841d2788674d.png)

Can you help me? Thank you very much!

**Comment by Asteria-BCSD** [comment]
Please check the new code.
