### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wanshangfeng** [Asteria-BCSD/Asteria#7]
Can you share the dataset with us? It will be very helpful for me.
Thanks

**Comment by joxeankoret** [comment]
Hi! I'm the author of Diaphora and I would like to have access to the dataset myself too. Thanks in advance!

**Comment by Asteria-BCSD** [comment]
We shared our binaries in dataset in https://drive.google.com/file/d/1NZALJqz5W4jowrhXdWWRfuT8fRJfBQ5z/view.
