### ISSUE TITLE
Can't get vul.sqlite

### ISSUE THREAD

**Issue by wanshangfeng** [Asteria-BCSD/Asteria#8]
While I run the cmd "python .\API_ast_generator.py --ida_path D:\IDA70\idat.exe --binary openssl-1.0.1s --database test.sqlite"
I can not get the test.sqlite file. And the output seems normal.
<img width="986" alt="image" src="https://user-images.githubusercontent.com/33548991/211757538-e84663ec-16e7-4509-9531-57fae446437a.png">

**Comment by Asteria-BCSD** [comment]
Can you pull the newest API_ast_generator and rerun the command above.
If there are no sqlite file generated, please check the ida.log and let us know the error log.

**Comment by Asteria-BCSD** [comment]
No response
